# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'donorsChoose' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for donorsChoose
  
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'Firebase/Core'
	
  target 'donorsChooseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'donorsChooseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
