# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
inhibit_all_warnings!

target 'donorsChoose' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for donorsChoose
  pod 'Fabric'
#  pod 'Answers'
  pod 'Crashlytics'
  pod 'Firebase/Core'
	
  target 'donorsChooseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'donorsChooseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
